version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    depends_on:
      - mongo
    restart: always
    build: .
    environment:
      - PORT=3000

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=banana
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
